a = input('digite algo: ')
print(f'o tipo primitivo desse valor é {type(a)}')
print(f'só tem espaço ? {a.isspace()}')
print(f'É númerico ? {a.isnumeric()}')
print(f'É alfabético ? {a.isalpha()}')
print(f'É alfanumérico? {a.isalnum()}')
print(f'Está em maiúsculas? {a.isupper()}')
print(f'Está em minúsculas? {a.islower()}')
print(f'Está capitalizada? {a.istitle()}')
