print('=-=-'*20)
print('                             MEDIA DO ALUNO')
print('=-=-'*20)
n1 = float(input('Primeira nota: '))
n2 = float(input('Segunda nota: '))
print(f'A sua media é {(n1 + n2) / 2:.1f}')
