nome = str(input('Digite seu nome completo: ')).strip()
primeiro = nome.split()
print('Muito prazer em te conhecer!')
print('Seu primeiro nome é {} '.format(primeiro[0]))
print('Seu último nome é {} '.format(primeiro[len(primeiro)-1]))